fix limit inheritance
TykTechnologies/tyk pull request #3331
Opened 2020-09-24 16:23 UTC by spetrunin

log correct limit in per field depth limit

## Description

## Related Issue
https://tyktech.atlassian.net/browse/TT-621

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2020-09-24 18:56 UTC, matiasinsaurralde approved these changes

2020-09-25 09:27 UTC, gernest requested changes
Looks good. Is it possible to have a test for this? We don't want this to be messed up in the future.

2020-10-14 13:38 UTC, sredxny approved these changes
LGTM

2021-05-14 08:22 UTC, pvormste requested changes
If you look at this PR: https://github.com/TykTechnologies/tyk/pull/3469/files you will see, that some of the code changed in the past and this PR would revert the changes in current state.

So you will need to adjust the code (tests are also failing because of this reason)

2021-05-14 08:22 UTC, pvormste commented on gateway/session_manager.go
> +	if l.DepthLimitEnabled(api.GraphQL.Enabled, accessDef) {
This code has been moved in a past PR. It now lives in `gateway/mw_graphql_complexity.go`

2021-05-14 08:22 UTC, pvormste commented on gateway/session_manager.go
> +func (l *SessionLimiter) DepthLimitEnabled(graphqlEnabled bool, accessDef *user.AccessDefinition) bool {
Now living in: `gateway/mw_graphql_complexity.go`

2021-05-14 08:22 UTC, pvormste commented on gateway/session_manager.go
> +func (l *SessionLimiter) DepthLimitExceeded(gqlRequest *graphql.Request, accessDef *user.AccessDefinition, schema *graphql.Schema) sessionFailReason {
This also is located in `gateway/mw_graphql_complexity.go`

2021-05-14 08:22 UTC, pvormste commented on gateway/session_manager_test.go
> +func TestSessionLimiter_DepthLimitEnabled(t *testing.T) {
Depth Limit tests are now located in: `gateway/mw_graphql_test.go`

2021-05-14 08:22 UTC, pvormste commented on gateway/session_manager.go
> +	sessionFailDepthLimit
I think this is not needed anymore

2021-05-14 13:29 UTC, pvormste approved these changes
Nice, all tests passing now! Good job

2021-05-18 11:31 UTC, urbanishimwe approved these changes

2021-05-18 11:37 UTC, gernest approved these changes

2021-05-18 11:37 UTC, merged

2021-05-18 11:37 UTC, spetrunin commented
/release to release-3

2021-08-17 21:12 UTC, tbuchaillot commented
@spetrunin this PR was missing in `release-3.2` and `release-3.2.2` branches.

2021-08-17 21:12 UTC, sredxny commented
/release to release-3.2

2021-08-17 21:24 UTC, sredxny commented
@spetrunin there're some issues merging this into release-3.2 and release-3.2.2, could you help us to include these changes?