add graphql websockets support (TT-904)
TykTechnologies/tyk pull request #3393
Opened 2020-11-18 10:40 UTC by pvormste

This PR adds support for websockets using the GraphQL websockets protocol.
To be able to use this feature, websockets need to be enabled for the gateway.

I have also set up a GraphiQL with websockets support that you can use for testing: 
https://github.com/pvormste/graphiql-websockets-tyk

Instructions are located in the readme.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

2020-11-20 07:51 UTC, spetrunin requested changes

2020-11-20 07:51 UTC, spetrunin commented on gateway/reverse_proxy.go
> +	res, hijacked, err = p.sendRequestToUpstream(roundTripper, outreq)
You could remove hijacked from `sendRequestToUpstream` method
```
res, err = p.sendRequestToUpstream(roundTripper, outreq)
return
```

2020-11-20 07:51 UTC, spetrunin commented on gateway/reverse_proxy.go
> +		return p.handleGraphQLIntrospection()
same could be done here
```
res, err = p.handleGraphQLIntrospection()
return
```

2020-11-23 11:39 UTC, spetrunin commented on gateway/mw_graphql.go
> +	if config.Global().HttpServerOptions.EnableWebSockets && websocket.IsWebSocketUpgrade(r) {
what if simplify conditions?
```go
	if websocket.IsWebSocketUpgrade(r) {
		if !config.Global().HttpServerOptions.EnableWebSockets {
			return errors.New("websockets are not allowed"), http.StatusUnprocessableEntity
		}

		if !m.websocketUpgradeUsesGraphQLProtocol(r) {
			return errors.New("invalid websocket protocol for upgrading to a graphql websocket connection"), http.StatusBadRequest
		}

		ctxSetGraphQLIsWebSocketUpgrade(r, true)
		return nil, http.StatusSwitchingProtocols
	}
```

2020-11-23 11:42 UTC, spetrunin approved these changes

2020-11-23 12:10 UTC, furkansenharputlu approved these changes
Looks good!

2020-11-23 12:49 UTC, merged

2020-11-23 12:49 UTC, pvormste commented
/release to release-3

2020-11-23 13:19 UTC, pvormste commented
manually merged to release-3