Log as much errors with vault and consul
TykTechnologies/tyk pull request #3407
Opened 2020-11-24 16:34 UTC by adelowo

## Description
Log errors if any when fetching keys from consul and value

## Related Issue

On a support call with a customer and we cannot retrieve data from Vault. Everything else seems right and i 
cannot find any more error per why the keys cannot be retrieved. 

## Motivation and Context

## How This Has Been Tested

Manually :) 

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

2020-11-25 13:36 UTC, gernest requested changes
I left a few suggestion. It is just a nit pick, its nice to be consistent when logging stuff with the rest of the gw.

2020-11-25 13:36 UTC, gernest commented on gateway/server.go
> +			log.WithError(err).Error(err)
```suggestion
			log.Error("Failed to setup consul: ", err)
```

2020-11-25 13:36 UTC, gernest commented on gateway/server.go
> +			log.WithError(err).Error(err)
```suggestion
			log.Error("Failed to setup vault: ", err)
```

2020-11-25 14:14 UTC, gernest approved these changes
LGTM

2021-08-19 18:40 UTC, furkansenharputlu approved these changes

2021-08-19 19:11 UTC, merged

2021-08-19 19:11 UTC, furkansenharputlu commented
/release to release-3-lts

2021-08-19 19:11 UTC, furkansenharputlu commented
/release to release-3.2

2021-08-19 19:12 UTC, furkansenharputlu commented
/release to release-4