replace graphql playground with tyk bundled graphiql
TykTechnologies/tyk pull request #3523
Opened 2021-04-08 10:50 UTC by spetrunin

## Description

Replaced graphql playground handlers provided by graphql-go-tools with a bundled version of GraphiQL with Explorer

## Related Issue

https://tyktech.atlassian.net/browse/TT-2120

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2021-04-08 11:26 UTC, alephnull requested changes
Since `templates/playground/index.html` is a new static file, it needs to be included in three places:
- deb and rpm files
- slim and std docker images
- tarballs
The good news is that this is all configured in one place, `.goreleaser.yml`. I'm happy to pair with you and make the changes in this PR itself. It shouldn't take more than an hour I think.

2021-04-08 11:41 UTC, buger commented
@alephnull I thought that we include the full folder. And since we added files to existing folder (https://github.com/TykTechnologies/tyk/tree/master/templates), it should just work https://github.com/TykTechnologies/tyk/blob/master/.goreleaser.yml#L82

2021-04-08 11:46 UTC, buger commented
Ah I see it looks only for json files now.

2021-04-08 13:44 UTC, jay-deshmukh commented on templates/playground/index.html
> +</html>
LGTM

2021-04-08 13:44 UTC, jay-deshmukh reviewed
LGTM

2021-04-09 08:14 UTC, pvormste approved these changes
Code LGTM - just consider @alephnull feedback

2021-04-09 15:29 UTC, buger commented
Looks good

2021-04-09 15:29 UTC, buger approved these changes

2021-04-12 15:20 UTC, alephnull approved these changes
LGTM :rocket:

2021-04-12 15:21 UTC, alephnull commented
Int image failure is due to gromit being down while I upgrade the integration envs.

2021-04-12 16:06 UTC, merged

2021-04-12 16:07 UTC, spetrunin commented
/release to release-3

2021-04-12 17:12 UTC, spetrunin commented
manually cherry-picked into release-3