TT-3793 query batching config
TykTechnologies/tyk pull request #3723
Opened 2021-11-05 07:32 UTC by urbanishimwe

This PR adds functionalities to enable or disable graphql query batching from API definitions

## Related Issue
https://tyktech.atlassian.net/browse/TT-3793

## Motivation and Context
check description of the above related issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

2021-11-08 10:19 UTC, spetrunin commented on apidef/api_definitions.go
> +	QueryBatching GraphQLQueryBatching `bson:"query_batching" json:"query_batching"`
Please and this switch on a Supegraph config via simple bool var

2021-11-08 10:19 UTC, spetrunin commented on apidef/api_definitions.go
> +// https://www.apollographql.com/blog/apollo-client/performance/batching-client-graphql-queries/
please remove link to apollo

2021-11-12 10:30 UTC, pvormste requested changes

2021-11-12 10:30 UTC, pvormste commented on apidef/api_definitions.go
> +	DisableQueryBactching bool                    `bson:"disable_query_batching" json:"disable_query_batching"`
Here's a typo: Should be `DisableQueryBatching`

2021-11-12 10:38 UTC, pvormste approved these changes

2021-11-12 13:30 UTC, spetrunin approved these changes

2021-11-16 05:46 UTC, merged

2021-11-16 05:46 UTC, urbanishimwe commented
/release to release-4

2022-01-03 13:07 UTC, pvormste commented
/release to release-4-lts