Added more details to the ssl_certificate config
TykTechnologies/tyk pull request #3726
Opened 2021-11-08 20:23 UTC by letzya

2021-11-09 13:37 UTC, zalbiraw approved these changes

2024-02-08 16:59 UTC, buger commented
<!-- add-pr-comment:mongo44-sha256 -->

**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/3726/merge
Commit: 237d117f418f977224909a925c823cb402e77dee 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7832885967)

2024-02-09 08:41 UTC, lghiur approved these changes

2025-02-19 18:18 UTC, buger commented
<p> A JIRA Issue ID is missing from your branch name, PR title and PR description! 🦄</p>
<p>Your branch: ssl_cert_definition</p>
<p>Your PR title: Added more details to the ssl_certificate config</p>
<p>Your PR description: 1.  Added more details to the `http_server_options.ssl_certificate` config
2. Added more details to the `certificate` config</p>
<p>If this is your first time contributing to this repository - welcome!</p>
<hr />
<p>Please refer to <a href="https://github.com/cleartax/jira-lint">jira-lint</a> to get started.
<p>Without the JIRA Issue ID in your branch name you would lose out on automatic updates to JIRA via SCM; some GitHub status checks might fail.</p>
Valid sample branch names:

  ‣ feature/shiny-new-feature--mojo-10'
  ‣ 'chore/changelogUpdate_mojo-123'
  ‣ 'bugfix/fix-some-strange-bug_GAL-2345'

2025-02-19 18:23 UTC, letzya commented on config/config.go
> +	// Deprecated. Replaced by `ssl_certificates`.
```suggestion
	// Deprecated: Use `ssl_certificates`instead.
```

2025-02-19 18:23 UTC, buger commented
<p> A JIRA Issue ID is missing from your branch name, PR title and PR description! 🦄</p>
<p>Your branch: ssl_cert_definition</p>
<p>Your PR title: Added more details to the ssl_certificate config</p>
<p>Your PR description: 1.  Added more details to the `http_server_options.ssl_certificate` config
2. Added more details to the `certificate` config</p>
<p>If this is your first time contributing to this repository - welcome!</p>
<hr />
<p>Please refer to <a href="https://github.com/cleartax/jira-lint">jira-lint</a> to get started.
<p>Without the JIRA Issue ID in your branch name you would lose out on automatic updates to JIRA via SCM; some GitHub status checks might fail.</p>
Valid sample branch names:

  ‣ feature/shiny-new-feature--mojo-10'
  ‣ 'chore/changelogUpdate_mojo-123'
  ‣ 'bugfix/fix-some-strange-bug_GAL-2345'

2025-02-20 10:12 UTC, buger commented
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>Open</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

2025-02-20 13:15 UTC, buger commented
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>Open</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

2025-02-20 13:20 UTC, buger commented
<p>I'm a bot and I 👍 this PR title. 🤖</p>

  <img src="https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif" width="400" />

2025-02-20 16:14 UTC, letzya commented
@titpetric can we merge this? not sure what I need to fix in the ci

2025-02-20 17:47 UTC, andyo-tyk requested changes
I don't think the terminology is accurate - have suggested alternatives.

2025-02-20 17:47 UTC, andyo-tyk commented on config/config.go
> +	// The certificate store of the Gateway.
The certificate store is in Redis - I think this is a reference to the certificates (presumably ID is an identifier assigned by Tyk when storing it in Redis?).

My suggestion and other comments assume this to be true.

```suggestion
	// Index of certificates available to the Gateway for use in client and upstream communication.
```

2025-02-20 17:47 UTC, andyo-tyk commented on config/config.go
> +	// 1. A certificate IDs
```suggestion
	// 1. The ID assigned to and used to identify a certificate in the Tyk Certificate Store
```

2025-02-20 17:47 UTC, andyo-tyk commented on config/config.go
> +	// 2. A path to a PEM file. The PEM file will have both the private key and the certificated concatenated.
```suggestion
	// 2. The path to a file accessible to the Gateway. This PEM file must contain the private key and public certificate pair concatenated together.
```

2025-02-20 17:47 UTC, andyo-tyk commented on config/config.go
> +	// SSL certificates used by Gateway server.
As this is deprecated, should we just remove this line? If it doesn't do anything we don't need to say what it no longer does.

```suggestion
```

2025-02-21 09:40 UTC, andyo-tyk approved these changes
Thanks - happy to approve. Definitely improves the docs.

2025-02-23 10:00 UTC, lghiur approved these changes

2025-04-07 09:58 UTC, merged