request and res log obfuscation
TykTechnologies/tyk pull request #3981
Opened 2022-03-31 14:48 UTC by urbanishimwe

This is an updated version of https://github.com/TykTechnologies/tyk/pull/3896
It contains most of the changes made by @joshblakeley and some refactoring.

## Description
Enables editing or removal of all parts of analytics records and raw request and responses recorded by Tyk at the gateway level.

## Related Issue
https://tyktech.atlassian.net/browse/TT-4793

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

2022-03-31 15:04 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit:  
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2071786371)

2022-04-04 14:21 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 36c8ee7819c060e0ae5803beaa739e5ffd02a673 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2090394820)

2022-04-04 14:42 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: e73b1ccc1a9c993378a7a11bf3f6af777e1d37ff 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2090527173)

2022-04-05 08:00 UTC, titpetric requested changes

2022-04-05 11:36 UTC, urbanishimwe commented on gateway/analytics.go
> +		return nil, fmt.Errorf("geoIPDB lookup of %q failed: %v", ipStr, err)
Another Linter report this as wrong format arg for type interface{}

2022-04-05 11:36 UTC, urbanishimwe commented on gateway/analytics_go_plugin.go
> +			err = fmt.Errorf("%v", e)
Another Linter report this as wrong format arg for type interface{}

2022-04-05 11:51 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 6675cf3b1158cedf440aa9ff205bf52677feafa3 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2095873781)

2022-04-05 11:53 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 2dadfc0d4d4fd4b3a2e6d1a7ff6d9e9cbff8197a 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2095882567)

2022-04-05 12:59 UTC, titpetric approved these changes

2022-04-06 08:09 UTC, jeffy-mathew approved these changes

2022-04-08 09:19 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 1fc116e6752c605073d53f213a628e4b92390a44 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2114180827)

2022-04-08 14:29 UTC, furkansenharputlu commented on gateway/analytics.go
> +	}
Can you please skip line after `if` and `for` blocks, it makes the code unreadable.

2022-04-11 11:22 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: a58bfb2da1c88b4ffd70d084e4684067a06f26ad 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2148073699)

2022-04-11 15:39 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: df31ce6d8123d054c1dc9ec408f8c394392d8518 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2149493049)

2022-04-11 16:02 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: f848ea88a1488fd29bcadd8978970833f825c06a 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2149628243)

2022-04-12 11:43 UTC, furkansenharputlu approved these changes

2022-04-12 11:44 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 4e480a9963934e097e86ac20f9437be5f507d5ce 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2154612558)

2022-04-12 11:48 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: ef9a52adc61c4ed06f11cdeec5ba99064ab01f82 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2154643590)

2022-04-12 12:56 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 074cbcc3d8ada653edd72ab0a11fa60fac101218 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2154995764)

2022-04-14 13:32 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 38e8f620e24e39cdab172789de069f41bca628e6 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2167418625)

2022-04-18 11:58 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/3981/merge
Commit: 0780bdf953863edc9ecc637735694020bef93b0c 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2183696117)

2022-04-18 12:14 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3981/merge
Commit: 0780bdf953863edc9ecc637735694020bef93b0c 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2183696117)

2022-04-18 12:41 UTC, merged

2022-04-18 12:41 UTC, lghiur commented
/release to release-4

2022-04-18 12:55 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 4a365db93acf41289d726900e44b4609877e7ce9 [TT-4793] request and res log obfuscation (#3981)

This is an updated version of https://github.com/TykTechnologies/tyk/pull/3896
It contains most of the changes made by @joshblakeley and some refactoring.

## Description
Enables editing or removal of all parts of analytics records and raw request and responses recorded by Tyk at the gateway level.

## Related Issue
https://tyktech.atlassian.net/browse/TT-4793

## Types of changes
<!-- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

Co-authored-by: joshblakeley <josh@tyk.io>
Co-authored-by: Jeff <jeffy.mathew100@gmail.com>
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2183903231)