Fix plugin build script
TykTechnologies/tyk pull request #3998
Opened 2022-04-07 16:41 UTC by asutosh

## Description
Update plugin compiler smoke tests to align with  the new changes in plugin compiler  build where the plugin name has version and platform info in the name, 
Also fix the plugin compiler build script - there seems to be an issue when there's an internal dependency in the `go.mod` file(eg: `github.com/TykTechnologies/tyk/certs`) - it causes the build to fail as it causes the the source tree to be deleted while building the plugin.

2022-04-07 16:55 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3998/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2110323559)

2022-04-08 17:41 UTC, buger commented on ci/tests/plugin-compiler/test.sh
> +mv testplugin/testplugin*.so testplugin/testplugin.so
Why we need this on master?
Plugin compiler for master generate output files with architecture and version in file name. 
Master gateway knows how to load such files. 
So this line should be only in release-4-lts branches I guess, which not yet support such plugin names?
And even release-4 (upcoming release-4.1) should support it just fine too... 

**UPDATE**
On the other thought I realized that in this test we load plugin via file, which kinda force you change file name in API definition every time. I raise this as a bug for this functionality here https://tyktech.atlassian.net/browse/TT-4354. 
Now this line does makes sense.

2022-04-08 17:41 UTC, buger commented on ci/tests/plugin-compiler/test.sh
> +mv testplugin/testplugin*.so testplugin/testplugin.so
Why we need this on master?
Plugin compiler for master generate output files with architecture and version in file name. 
Master gateway knows how to load such files. 
So this line should be only in release-4-lts branches I guess, which not yet support such plugin names?
And even release-4 (upcoming release-4.1) should support it just fine too... 

**UPDATE**
On the other thought I realized that in this test we load plugin via file, which kinda force you change file name in API definition every time. I raise this as a bug for this functionality here https://tyktech.atlassian.net/browse/TT-4354. 
Now this line does makes sense.

2022-04-11 09:36 UTC, alephnull commented
Needs a rebase.

2022-04-11 09:44 UTC, alephnull requested changes
Since we depends on GOPATH, and its status is somewhat nebulous 1.16 onwards, please consider adding
```
[ -z $GOPATH ] && { echo Please set GOPATH; exit 1 }
```
to the top of the script. As a belt and braces thing, perhaps also explicitly set GOPATH via ENV in the image.

2022-08-31 23:20 UTC, blagerweij commented
We've used a different approach than the proposed `go mod vendor` solution:

```
cd $TYK_SOURCE_PATH
go list -m -f '{{ if not .Main }}{{ .Path }} {{ .Version }}{{ end }}' all > dependencies.txt

# for any dependency also present in Tyk, change the module version to Tyk's version
cd $PLUGIN_SOURCE_PATH

# remove go module information
rm -rf go.mod go.sum

# initialize fresh module
go mod init mymodule

# add graphql-go-tools pinned version
go mod edit -replace github.com/jensneuse/graphql-go-tools=github.com/TykTechnologies/graphql-go-tools@$GOTOOLS_REF

# add Tyk version
go get github.com/TykTechnologies/tyk@$TYK_REF

# scan and update go dependencies
go mod tidy

# collect all plugin dependencies
go list -m -f '{{ if not .Main }}{{ .Path }} {{ .Version }}{{ end }}' all > dependencies.txt

# for any shared dependency, pin the version to Tyk gateway version
awk 'NR==FNR{seen[$1]=$2; next} seen[$1] && seen[$1] != $2' $PLUGIN_SOURCE_PATH/dependencies.txt $TYK_SOURCE_PATH/dependencies.txt | while read PKG VER; do
  go mod edit -replace=$PKG=$PKG@$VER
done
```
This uses Go modules 'replace' behaviour to fix versions for any dependency which is shared with Tyk gateway.

By tweaking the Docker images for plugin-compiler a bit, we can ensure that listing all dependencies for Tyk gateway is done ahead of time (during the creation of the Docker image), since these dependencies are fixed for a specific version of Tyk

2022-09-01 01:57 UTC, alephnull commented
Hey @asutosh would you follow up on this?

2022-09-01 01:58 UTC, alephnull commented
https://tyktech.atlassian.net/browse/TT-6402 seems to indicate that GOOS and GOARCH cannot be overridden on the command line.

2022-09-01 06:23 UTC, asutosh commented
Thanks @blagerweij ! 
Will follow up on your suggested changes.

2024-05-02 06:47 UTC, closed without merging