backport f62d601
TykTechnologies/tyk pull request #4290
Opened 2022-09-06 20:45 UTC by sredxny

## Description

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2022-09-07 07:21 UTC, tbuchaillot requested changes
@sredxny you are missing an important part in the `PurgeCache` part.

`
exp, _ := r.Store.GetExp(analyticsKey)
if exp == -1 {
	r.Store.SetExp(analyticsKey, int64(expireAfter))
            ...
`

the `if exp == -1` instead of `if exp <= 0` is key since we just want to set the expiration when it's not set.

2022-09-07 15:54 UTC, sredxny commented
@tbuchaillot good catch!! done

2022-09-08 06:34 UTC, tbuchaillot requested changes

2022-09-08 06:34 UTC, tbuchaillot commented on gateway/redis_analytics_purger.go
> +	if exp <= -1 {
@sredxny this should be exp = -1. If TTL is -2, it means that the key doesn't exist so we don't want to set anything there.

2022-09-08 17:10 UTC, tbuchaillot approved these changes
LGTM - please check standalone gw and mdcb scenarios before merge 👌

2022-09-09 12:17 UTC, merged