[TT-7057] add info about the default value
TykTechnologies/tyk pull request #4496
Opened 2022-12-06 20:11 UTC by letzya

Ticket https://tyktech.atlassian.net/browse/TT-7057

## Description

Explain what the default value is (and if it's zero)
https://tyk.io/docs/tyk-oss-gateway/configuration/#http_server_optionsread_timeout

## Related Issue

## Motivation and Context

## How This Has Been Tested

Haven't tested the script that updated the docs

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
Update comment

## Checklist

- [X] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2022-12-06 20:30 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4496/merge
Commit:  
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3633092204)

2022-12-07 09:50 UTC, tbuchaillot approved these changes
LGTM

2022-12-07 19:08 UTC, zalbiraw requested changes

2022-12-07 19:08 UTC, zalbiraw commented on config/config.go
> +	// User -> Gateway network read timeout. Not setting this config, or setting this to 0, defaults to 120 seconds
I would say this should client -> Gateway?

2022-12-07 19:23 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4496/merge
Commit: 64144f676692bc646eb02eb3d4b8fbe3496c9c25 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3641998219)

2022-12-07 19:28 UTC, zalbiraw approved these changes
LGTM!

2022-12-07 19:48 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4496/merge
Commit: 2e09d6ae31a8db248611b75b828d699786929014 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3642156462)

2022-12-08 14:18 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4496/merge
Commit: 93a82dd39cb156329aeb6f20fb0b73a004719603 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3648952532)

2022-12-08 14:37 UTC, merged

2022-12-08 14:56 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 545234c830d5ab5c89b9cabc330122b415094998 [TT-7057] add info about the default value (#4496)

<!-- Provide a general summary of your changes in the Title above -->
Ticket https://tyktech.atlassian.net/browse/TT-7057

## Description

<!-- Describe your changes in detail -->

Explain what the default value is (and if it's zero)

https://tyk.io/docs/tyk-oss-gateway/configuration/#http_server_optionsread_timeout

## Related Issue

<!-- This project only accepts pull requests related to open issues. -->
<!-- If suggesting a new feature or change, please discuss it in an
issue first. -->
<!-- If fixing a bug, there should be an issue describing it with steps
to reproduce. -->
<!-- OSS: Please link to the issue here. Tyk: please create/link the
JIRA ticket. -->

## Motivation and Context

<!-- Why is this change required? What problem does it solve? -->

## How This Has Been Tested

<!-- Please describe in detail how you tested your changes -->
<!-- Include details of your testing environment, and the tests -->
<!-- you ran to see how your change affects other areas of the code,
etc. -->
<!-- This information is helpful for reviewers and QA. -->
Haven't tested the script that updated the docs

## Screenshots (if appropriate)

## Types of changes

<!-- What types of changes does your code introduce? Put an `x` in all
the boxes that apply: -->

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)
Update comment

## Checklist

<!-- Go over all the following points, and put an `x` in all the boxes
that apply -->
<!-- If there are no documentation updates required, mark the item as
checked. -->
<!-- Raise up any additional concerns not covered by the checklist. -->

- [X] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why
Triggered by: push (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3649277166)