replaed apidef.ObjectID for id.OID WIP
TykTechnologies/tyk pull request #4802
Opened 2023-02-24 22:03 UTC by sredxny

## Description

apidefinition and policies are using the apidef.ObjectId object as id, as the storage library already implements its own id system is required to replace it here

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2023-02-24 22:16 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4802/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4266611894)

2023-02-25 00:31 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4802/merge
Commit: 26b72e730f4ec12b8689a193351399d7f95047dd 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4267331857)

2023-03-17 18:56 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 63412f0eeed57085628ac9432ed6cc22e0a64e02 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4450591309)

2023-03-17 21:06 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 664ef6ad4512058213678f05866eb638c5dca8b7 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4451470474)

2023-03-20 19:34 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: a5a2a5d885cda37d891282954d7276f3e73291c2 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4472013578)

2023-03-22 02:50 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4802/merge
Commit: 0aad32b6273dbae5536b74bb8bddf176e74657d9 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4485811678)

2023-04-05 20:07 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4802/merge
Commit: 1aa4b1f27e397ac940a10a3d5ec016de9e87a620 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4622266340)

2023-04-11 15:19 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 7b09fad784faf43b1d136b47bda00a3ed443257b 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4668958233)

2023-04-11 18:54 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 8c9d16ac8584f90aaaee62618f79fb496f4dfd69 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4670872402)

2023-04-12 08:18 UTC, titpetric commented on go.mod
> +	github.com/TykTechnologies/tyk-pump v1.7.0-rc1
@sredxny you missed a dependency bump here, this reverts pump and shouldn't

2023-04-13 16:17 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 8646e8231d58ea6d85513bca6b9ac7ba2314beb4 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4691305794)

2023-04-17 15:28 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4802/merge
Commit: b0cd7efded5bc563f61a992a36bdcf297912d4d0 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4722755165)

2023-04-17 15:37 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: b2de4bb93c25d872333364ea650992738bac89f6 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4722853790)

2023-04-17 20:01 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 378c602b1c9681f97feeb3704717e53aa4f497bf 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4725159351)

2023-04-17 20:19 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 4afa000c202624515d35f59b19e429d7f4caa243 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4725272304)

2023-04-18 11:49 UTC, tbuchaillot approved these changes

2023-04-18 12:23 UTC, mativm02 requested changes

2023-04-18 12:23 UTC, mativm02 commented on go.sum
> +go.mongodb.org/mongo-driver v1.11.2/go.mod h1:s7p5vEtfbeR1gYi6pnj3c3/urpbLv2T5Sfd6Rp2HBB8=
@sredxny why do we need this?

2023-04-18 12:25 UTC, mativm02 approved these changes

2023-04-20 02:59 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 8589e598fa074e76e9b3cc0e385c3e26c6ce884e 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4749927894)

2023-04-20 16:33 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 20b80d82ef376244a0d1f3c7cf846eeacf22337b 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4756497365)

2023-04-21 15:07 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: 5ff34b1e96f9503b677bac745ab7677ada12008e 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4766073237)

2023-04-25 16:46 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4802/merge
Commit: b9e13c58d0e223a397d64761852df77944df6f78 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4799848570)

2023-04-25 16:50 UTC, merged