[CI] Sync automation: Syncing commits from master
TykTechnologies/tyk pull request #4809
Opened 2023-02-27 14:54 UTC by Tyk-ITS

PR auto generated by the CI Sync automation.
          Picks the CI changes from the commit c7bff4974805f41a0e1dd120501abe119df55010
          on master.
          Please make any additional changes required before
          merging.

2023-02-27 14:57 UTC, alephnull approved these changes

2023-02-27 14:59 UTC, alephnull requested changes

2023-02-27 14:59 UTC, alephnull commented on ci/goreleaser/goreleaser-el7.yml
> +    - internal
@asutosh this line is wrong right?

2023-02-27 15:16 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4809/merge
Commit:  
Triggered by: pull_request (@Tyk-ITS)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4283682186)

2023-03-02 09:53 UTC, asutosh commented
Closing stale sync-automation PR

2023-03-02 09:54 UTC, closed without merging