[TT-7808] In proxy-only mode, GraphQL query return errors from upstream
TykTechnologies/tyk pull request #5049
Opened 2023-05-23 13:10 UTC by buraksezer

PR for [TT-7808](https://tyktech.atlassian.net/browse/TT-7808)

We pass the upstream headers and status codes to the client in proxy-only mode. This is an existing feature. With this PR, we start attaching the upstream's error messages to the response. 

For example, say that a GraphQL service returns the following, non-standard error message with HTTP 401 status code:

```json
{"message": "Unauthorized"}
```

We return the following error message with HTTP 401 message to the client:

```json
{
    "errors": [
        {
            "message": "unable to resolve",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ]
        }
    ],
    "data": null
}
```

It was not possible to reach out to the original error message from upstream. With this PR, we started returning the following error message with HTTP 401 status code:

```json
{
    "errors": [
        {
            "message": "unable to resolve",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "extensions": {
                "message": "Unauthorized"
            }
        }
    ],
    "data": null
}
```

A new configuration item has been added to the API definition(`graphql.proxy.return_errors_from_upstream`). This solution is only valid for proxy-only mode and we only keep the original response if upstream returns an error(status code >= 400).

[TT-7808]: https://tyktech.atlassian.net/browse/TT-7808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-05-23 13:38 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5057718977)

2023-05-23 13:45 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit: 537ad345a516bf11db257a5f83a6bd31758e822f 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5057774099)

2023-05-23 13:48 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit: b4b95066c0d6adf0f18a7cfddd6cad9be864539c 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5057884091)

2023-05-24 08:59 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit: 623946e32f71fac5323d74a7a8fba5b7b6c8ec62 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5066510082)

2023-05-24 11:54 UTC, pvormste requested changes

2023-05-24 11:54 UTC, pvormste commented on apidef/api_definitions.go
> +	ReturnErrorsFromUpstream bool              `bson:"return_errors_from_upstream" json:"return_errors_from_upstream"`
To make this feature proof maybe we can create a new struct here:
```go
UseResponseExtensions GraphQLResponseExtensions `bson:"use_response_extensions" json:"use_response_extensions"`

type GraphQLResponseExtensions struct {
    OnErrorForwarding bool `bson:"on_error_forwarding" json:"on_error_forwarding"`
}
```

which results in
```json
"proxy": {
        "auth_headers": {},
        "request_headers": null,
        "use_response_extensions": {
             "on_error_forwarding": true
        }
    },
```
Feel free to adjust this idea

2023-05-24 12:39 UTC, titpetric commented on gateway/mw_graphql_transport.go
> +		proxyOnlyCtx.originalResponseBody = bytes.NewReader(body)
Can you consider using `nopCloserBuffer` or `nopCloser`, both exist in reverse_proxy.go, and could be isolated and moved into /internal/httputil; they allow for re-reading of an io.ReadCloser, which should match request or response bodies.

2023-05-24 13:08 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit: 9fe85398d78d2f5656c618a61983169c17d537b4 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5068820130)

2023-05-24 13:09 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit: 04bb5d34aef2bf0cc1242c125fd6cf14ef41b528 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5068818825)

2023-05-24 13:20 UTC, pvormste approved these changes

2023-05-24 14:13 UTC, kofoworola approved these changes

2023-05-24 14:36 UTC, merged

2023-05-24 14:38 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5049/merge
Commit: d8f896aadcd9dfc653edb0ccd7681f5d2920f80b 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5069773944)

2023-05-25 08:16 UTC, buraksezer commented
/release to release-5.1

2023-05-25 08:19 UTC, buraksezer commented
/release to release-4-lts

2023-06-02 09:20 UTC, pvormste commented
/release to release-5.1