Changes to MaxRequestBodySize comment
TykTechnologies/tyk pull request #5071
Opened 2023-05-31 12:30 UTC by andyo-tyk

Changes following review of DX-311

## Description

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2023-05-31 12:33 UTC, andyo-tyk commented
This relates to changes in TT-5186

2023-05-31 12:35 UTC, lghiur approved these changes

2023-05-31 18:31 UTC, Tyk-ITS commented
**API tests result: cancelled** :no_entry_sign: 
Branch used: refs/pull/5071/merge
Commit:  
Triggered by: pull_request (@andyo-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5132849031)

2023-06-07 11:52 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5071/merge
Commit: 5fa8058f5099e54758353e07f56913f181f2fe16 
Triggered by: pull_request (@andyo-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5199460132)

2023-06-07 15:36 UTC, dcs3spp requested changes
Apologies Andy, I forgot to comment the suggestion string text for `MaxRequestBodySize` in config.go.

I have added suggestion for commit

2023-06-07 15:50 UTC, dcs3spp commented on config/config.go
> +// MaxRequestBodySize configures a maximum size limit for request body size (in bytes) for all APIs on the Gateway.
```suggestion
	// MaxRequestBodySize configures a maximum size limit for request body size (in bytes) for all APIs on the Gateway.
```

2023-06-07 16:59 UTC, titpetric approved these changes
LGTM

2023-06-08 09:58 UTC, dcs3spp approved these changes
lgtm

2023-06-08 10:31 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5071/merge
Commit: 8b3394caa0b64ead1ab06d5fd354bc28340ca510 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5209831026)

2023-06-08 11:58 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5071/merge
Commit: 8b3394caa0b64ead1ab06d5fd354bc28340ca510 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5209831026)

2023-06-17 12:20 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5071/merge
Commit: 8b3394caa0b64ead1ab06d5fd354bc28340ca510 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5209831026)

2023-06-17 12:36 UTC, merged

2023-06-17 12:37 UTC, lghiur commented
/release to release-5.1

2023-06-17 12:37 UTC, lghiur commented
/release to release-5.1.0

2023-06-17 12:43 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5071/merge
Commit: 406d44db3cea4ddf585ead15150497e6dc9fc2e4 
Triggered by: pull_request (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5298101521)