[TT-9199]: Restore all files tracked by sync automation.
TykTechnologies/tyk pull request #5177
Opened 2023-06-20 13:32 UTC by asutosh

## Description

Restores ci/*, .github/workflows/{release.yml,api-tests.yml,ci-tests.yml} to the state before the
commit 0e27df86ae5f9808158b4a875fd03b357b7bef48 (go-1.19 changes automatically picked by sync-automation from master)

## Related Issue
TT-9199

2023-06-20 13:49 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5323224868)

2023-07-04 10:53 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: bf467b4bf18b26723ce8daafd78345ca70068366 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5453712951)

2023-07-04 10:56 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: ada86d01c9251eb3cb6644e8711732a304808343 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5453716032)

2023-07-04 11:12 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: 44ff375b763db3ce4b807c577b642ce197cb84b5 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5453874729)

2023-07-04 12:06 UTC, ermirizio requested changes

2023-07-04 12:06 UTC, ermirizio commented on .github/workflows/api-tests.yml
> +          echo "::set-output name=branch::${{ github.ref	}}"
Revert this to $GITHUB_OUTPUT please

2023-07-04 13:49 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: bcd90370b33829d8fbb492f4ff1f5c5d74c0047d 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5455296862)

2023-07-05 09:52 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: 6b9053be4c3ab7842924791fa4b476afc357cde2 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5462727329)

2023-07-05 09:56 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5462758604)

2023-07-05 10:21 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: 55d28b46e9f52906f8612fdb3f78c0af52657ceb 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5462953322)

2023-07-05 10:38 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: a9007d4a9e89ceab4d1a0b8bb385efa3ee8deb67 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5463122892)

2023-07-06 15:07 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: 7ef0d376e7eb29d21cd17b52538435260cf41848 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5476883559)

2023-07-12 10:13 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5177/merge
Commit: f9f3a42ecb7d29d07b293e90a3da2c9677b41716 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5530172402)

2023-07-12 11:13 UTC, titpetric reviewed
Some locations (github, ci/goreleaser, ci/images/plugin-compiler) have healthy versions on 4.0.14

2024-05-02 06:48 UTC, closed without merging