[TT-9169/TT-9341] update docs
TykTechnologies/tyk pull request #5264
Opened 2023-07-04 09:42 UTC by jeffy-mathew

## Description

Add config doc to let users know `disable_key_actions_by_username` should the same in dashboard

## Related Issue

https://tyktech.atlassian.net/browse/TT-9341

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2023-07-04 10:00 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5264/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5453218615)

2023-07-04 10:22 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5264/merge
Commit: c8479ebf9c77ae071b54ca1cd0e13dfdab618802 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5453392861)

2023-07-05 07:49 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5264/merge
Commit: 02fc3b400a1bb09cd082b83d88b2208aed81013e 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5461580616)

2023-07-05 14:11 UTC, andyo-tyk commented on config/config.go
> +	// Please ensure that dashboard has the same value for seamless functionality.
```suggestion
	// When this is set to `true` you are able to search for keys only by keyID or key hash (if `hash_keys` is also set to `true`)
	// If you are using the Tyk Dashboard, you must configure this setting with the same value in both Gateway and Dashboard
```

2023-07-05 14:41 UTC, andyo-tyk requested changes
Updated to clarify behaviour with basic auth and hashed keys

2023-07-05 14:41 UTC, andyo-tyk commented on config/config.go
> +	// Please ensure that dashboard has the same value for seamless functionality.
```suggestion
	// When this is set to `true` you are able to search for keys only by keyID or key hash (if `hash_keys` is also set to `true`)
	// Note that if `hash_keys` is also set to `true`, then the keyID will not be provided for APIs secured using basic auth so the only search option would be using key hash
	// If you are using the Tyk Dashboard, you must configure this setting with the same value in both Gateway and Dashboard
```

2023-07-05 17:07 UTC, dcs3spp approved these changes
lgtm

2023-07-06 12:50 UTC, andyo-tyk commented on config/config.go
> +	// Note that if `hash_keys` is also set to `true`, then the keyID will not be provided for APIs secured using basic auth so the only search option would be using key hash
```suggestion
	// Note that if `hash_keys` is also set to `true` then the keyID will not be provided for APIs secured using basic auth. In this scenario the only search option would be to use key hash
```

2023-07-07 13:22 UTC, andyo-tyk approved these changes

2023-07-07 13:43 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5264/merge
Commit: 088a11e884421e1b0122f3329597e730a172f276 
Triggered by: pull_request (@andyo-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5486887772)

2023-07-07 14:14 UTC, merged

2023-07-07 14:20 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5264/merge
Commit: 01cfc0a6692da750dce54792b42387b742d5f06e 
Triggered by: pull_request (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487198515)