[TT-7902] Detailed Tracing
TykTechnologies/tyk pull request #5294
Opened 2023-07-07 13:55 UTC by mativm02

## Description

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2023-07-07 14:15 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5294/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487178244)

2023-07-07 14:52 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5294/merge
Commit: 10c54c7086299040c579a05e0913b10658f86559 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487512535)

2023-07-07 15:17 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5294/merge
Commit: 45f08e1f5241309e07ce5a591e056de416053737 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487748354)

2023-07-10 13:05 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 0b50bb79639e658c9f208dc48abd748d9131681b 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5508224877)

2023-07-10 13:07 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 6027a77f3c008aad12f172b09c64c2cfd8adbe9e 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5508221362)

2023-07-10 13:15 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: b828b57dca6a1900af7000328bdd9c729733f28d 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5508302882)

2023-07-11 12:12 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 6bd64b74757361f81f55c158a639a1220a147250 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519565037)

2023-07-11 12:13 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: f0d6d7c29845b317b67e194ce20141064c7f76aa 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519566347)

2023-07-11 12:17 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5294/merge
Commit: eaa1139723147eb6e66aa9d14880552a01f0612a 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519432494)

2023-07-11 12:24 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: b24ad00a9c54df6b1b50a4c002a4749e73c0e24d 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519671645)

2023-07-11 12:24 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: b24ad00a9c54df6b1b50a4c002a4749e73c0e24d 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519671630)

2023-07-11 13:17 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: ae25d2adab9fea9799ca8e91235871599d008d8f 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5520229619)

2023-07-11 13:28 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 81d870224d3d1f52b9122f6a1899ed5341a123eb 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5520338853)

2023-07-12 12:32 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: de7556f903d6c4c6a7d7e95dd6557c8a0a0770f3 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5531411752)

2023-07-20 12:37 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: bb582fc45c0c401c866c8151e26216f0c30e72d2 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5610860950)

2023-07-20 15:17 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 5ffd2c65949485f184826a2ddbcf5cacc1c4dbba 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5612589518)

2023-07-21 12:43 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 1ee9a1f671b28ae0980354778289051952642b4d 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5622271274)

2023-07-21 12:46 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 3ff2a8b1a827616d438567ae27550f7d2e573421 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5622289665)

2023-07-24 12:53 UTC, mativm02 commented on Taskfile.yml
> +      - "./**/*.go"
change made by the linter

2023-07-24 12:53 UTC, mativm02 commented on Taskfile.yml
> +        task test:opentelemetry:test
I'm ensuring teardown is executed no matter if the test failed or not

2023-07-24 13:12 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: c3284a5e1b2e5c713f79435f38b78c1b3aed5188 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5645053376)

2023-07-24 13:46 UTC, tbuchaillot requested changes
Please add a test case  here with detailed spans  https://github.com/TykTechnologies/tyk/blob/master/gateway/api_loader_test.go#L434

2023-07-24 13:46 UTC, tbuchaillot commented on gateway/middleware.go
> +				span = tyktrace.SpanFromContext(r.Context())
Move this function to otel internal pkg, so we don't have to import /opentelemetry/trace here

2023-07-24 13:46 UTC, tbuchaillot commented on apidef/schema.go
> +        "detailed_tracing": {
Is this linted?

2023-07-24 14:47 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 6b8465653b8e0bb75b073222697205569d724d0f 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5646100321)

2023-07-25 14:19 UTC, mativm02 commented on apidef/schema.go
> +        "detailed_tracing": {
it is!

2023-07-25 14:43 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 6de24eeeec280883ca4a5a93d2b101cbe0f6ff9f 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5657988450)

2023-07-25 14:47 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 6f5619b20e5cb7a4fbb90afe9175ae59e7eec7fd 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5658068202)

2023-07-31 14:40 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 6b8465653b8e0bb75b073222697205569d724d0f 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5715836627)

2023-07-31 14:40 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5294/merge
Commit: 8c83546eca3609b0cdcddcfbc64e2d1b1924a3ab 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5715847807)

2023-07-31 17:15 UTC, merged