initial draft for local try
TykTechnologies/tyk pull request #5401
Opened 2023-08-09 19:10 UTC by ermirizio

Try to add mdcb

2023-08-11 11:39 UTC, ermirizio commented on ci/auto/dash-bootstrap.sh
> +sed ${sed_exp} "s/TYK_GW_SLAVEOPTIONS_RPCKEY=.*/TYK_GW_SLAVEOPTIONS_RPCKEY=${orgid}/g" *.env
This variable is required for GW SLAVES to connect with MDCB. Is propagated to all env files in the root folder using SED. Not a very elegant approach

2023-08-11 11:39 UTC, ermirizio commented on ci/auto/dash-bootstrap.sh
> +sed ${sed_exp} "s/TYK_GW_SLAVEOPTIONS_APIKEY=.*/TYK_GW_SLAVEOPTIONS_APIKEY=${user_auth}/g" *.env
This variable is required for GW SLAVES to connect with MDCB. Is propagated to all env files in the root folder using SED. Not a very elegant approach

2023-08-11 11:40 UTC, ermirizio commented on ci/auto/dash-bootstrap.sh
> +sed ${sed_exp} "s/USER_API_SECRET=.*/USER_API_SECRET=${user_auth}/g" *.env
This variable plays the same role as above but, is used for MDCB tests, will get replaced into a new env file exclusively for pytest called pytest.env

2023-08-11 11:41 UTC, ermirizio commented on ci/auto/local-mongo44.env
> +TYK_GW_SLAVEOPTIONS_APIKEY=placeholder
This variables shouldn't be here, we need to find another place that makes this sustainable.

2023-08-11 11:41 UTC, ermirizio commented on ci/auto/local-postgres15.env
> +TYK_GW_SLAVEOPTIONS_APIKEY=placeholder
This variables shouldn't be here, we need to find another place that makes this sustainable.

2023-08-14 02:41 UTC, ermirizio commented
@alephnull I have reverted all the changes you requested and modifications have been done as well:

- Separated files compose for pro and proha
- pro-ha folder with configuration files
- Added dash-bootstrap script for mdcb config
- A taskfile has been added for developers to be able to reproduce this locally. Feel free to remove it if you consider it doesn't add any value.

2023-08-15 07:17 UTC, alephnull requested changes
The new env vars in local-*.env files need to find a good home.

Also, the comments on dash_bootstrap.sh need to become TODOs in the code.

2023-08-28 23:29 UTC, ermirizio commented
In favour of https://github.com/TykTechnologies/tyk/pull/5477

2023-08-28 23:29 UTC, closed without merging