Add reload interval
TykTechnologies/tyk pull request #5418
Opened 2023-08-14 18:53 UTC by zalbiraw

## Description

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2023-08-14 19:10 UTC, Tyk-ITS commented
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5418/merge
Commit:  
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5859505584)

2023-08-14 19:18 UTC, zalbiraw commented
/release to release-4.3.8

2023-08-14 19:18 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5418/merge
Commit: 0caf819354b469873f0c098d94f66f2a5ebf16df 
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5859545657)

2023-08-31 10:05 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5418/merge
Commit: ba780fc88f34d018e75b093b9534c8321107529b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6035706382)

2023-08-31 11:37 UTC, jeffy-mathew approved these changes

2023-08-31 11:58 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5418/merge
Commit: 26fe9aedcfce79fa589a53089d6c7f09ba28605a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6036782854)

2023-08-31 12:16 UTC, dcs3spp requested changes
@titpetric

// Sets the default wait interval in seconds to check for Gateway reload?

2023-08-31 12:16 UTC, dcs3spp commented on config/config.go
> +	// Sets the default interval for how often to reload the gateway when getting reload instructions in seconds.
Sets the default wait interval in seconds to check for Gateway reload?

2023-08-31 12:58 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5418/merge
Commit: ebca49efd752b8655778d8ca415c533c3950ca68 
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6037397380)

2023-08-31 13:04 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5418/merge
Commit: 317a5333021279c1704575fc7ee20017aa6b3297 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6037442723)

2023-08-31 13:06 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5418/merge
Commit: cf3aed71e4fcad9e3643ccc515b5b5664884d950 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6037489671)

2023-08-31 14:09 UTC, dcs3spp approved these changes

2023-08-31 14:09 UTC, merged

2023-08-31 14:10 UTC, titpetric commented
/release to release-5.2

2023-08-31 14:10 UTC, titpetric commented
/release to release-4.3.8

2023-08-31 14:11 UTC, titpetric commented
/release to release-5-lts

2023-09-01 17:32 UTC, zalbiraw commented
/release to release-4.3.8

2023-09-01 17:47 UTC, zalbiraw commented
/release to release-4.3.8

2023-11-06 11:03 UTC, titpetric commented
/release to release-4-lts