[TD-2132] Tyk-GW / Add proha to api-test wflow
TykTechnologies/tyk pull request #5477
Opened 2023-08-28 23:29 UTC by ermirizio

Add pro-ha flavour to api-tests matrix

2023-08-28 23:49 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6006019676)

2023-08-29 03:57 UTC, alephnull requested changes
I think we can use pro-ha.yml exclusively.

2023-08-29 03:57 UTC, alephnull commented on .github/workflows/release.yml
> +        flavour: [ "pro", "pro-ha" ]
I think we just need pro-ha here. At least for PRs.

2023-08-30 04:00 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: a6967c786754acecd3b7a9ad1612b7469071a927 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6020269395)

2023-08-30 13:19 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: c6e2bec65b3ff59d91395644a059698ac8aef2af 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6025150465)

2023-08-30 20:13 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 1f4cb84fb1c22e3ffc5dec752822c1afa757cbfc 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6029420101)

2023-08-31 17:15 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 551ebc36452c316a9ce715413582c939ca9a18b6 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6040216334)

2023-08-31 17:21 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: f13509f5dbdac0c44d33a2c4982700819529e38e 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6040231861)

2023-09-01 14:14 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 1fb17f4b95acc42a7737c91e7887ca53f2e80234 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6050263061)

2023-09-01 14:33 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 0e8a4903242169fe48676fd708197f5bd17f0eea 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6050485877)

2023-09-01 15:28 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 933e7a4a4ab7504b2af36d73e7bfd697b89b85b9 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6051046300)

2023-09-05 15:13 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 03d3dea4fafe0e1f2ead8f9b0baf29693d8f5378 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6086269652)

2023-09-11 19:29 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 95950e588f722689adbc91e9c2f1dff25593aa55 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6150680908)

2023-09-11 20:03 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: d75f29268e5d102b6c81dfb2089d34c4c7034dbe 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6150993597)

2023-09-11 20:17 UTC, Tyk-ITS commented
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5477/merge
Commit: 1a4599482e6b3ea73ea9c004536dae27af5f6249 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6151116676)

2023-09-12 07:56 UTC, alephnull requested changes

2023-09-12 07:56 UTC, alephnull commented on .github/workflows/release.yml
> +        flavour: [ "pro-ha" ]
I don't think this is required at this point. `release.yml` runs for PRs and I feel it is overkill to run this for more than one flavour.

2023-09-12 07:56 UTC, alephnull commented on .github/workflows/release.yml
> +          confs_dir=./"${{ matrix.flavour }}"
```suggestion
          confs_dir=./pro-ha
```
This env can be used in relevant repos for PRs.

2023-09-12 07:56 UTC, alephnull commented on .github/workflows/release.yml
> +          docker run --rm --network auto_default --env-file ${auto_dir}/pytest.env \
I think it is better to add the contents of pytest.env into pro-ha.yml.

2023-09-12 18:15 UTC, ermirizio commented
Closing this in favour of https://github.com/TykTechnologies/tyk/pull/5553 , all changes have been ported there.

2023-09-12 18:15 UTC, closed without merging