TT-12306, addressed changes suggested in the tyk-docs PR
TykTechnologies/tyk pull request #6377
Opened 2024-06-26 13:12 UTC by andrei-tyk

## Description

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2024-06-26 13:38 UTC, dcs3spp approved these changes
Thanks @andrei-tyk I have approved PR

2024-06-26 14:12 UTC, dcs3spp commented
If ReadableDuration is and alias also can that also be hidden before the merging?

2024-06-26 15:00 UTC, dcs3spp reviewed
If ReadableDuration is an alias also can that also be hidden before merging?

2024-06-27 09:23 UTC, dcs3spp approved these changes
Thanks @andrei-tyk I've approved the update

2024-06-27 09:54 UTC, titpetric commented on apidef/oas/event.go
> +// nolint
This is probablly wrong,...

2024-06-27 09:55 UTC, titpetric requested changes

2024-06-27 09:55 UTC, titpetric commented on apidef/oas/event.go
> +// nolint
Remove `// nolint` hints, if the intent is to skip some symbols, we need to adjust the CI action.
We already skip a few symbols from getting exported to docs here:
https://github.com/TykTechnologies/exp/blob/main/.github/workflows/tyk-docs.yml#L154

2024-07-01 10:31 UTC, lghiur approved these changes

2024-07-01 11:21 UTC, merged