[TT-12775] Request size limit breaks GET and DELETE requests
TykTechnologies/tyk pull request #6734
Opened 2024-12-02 09:26 UTC by buraksezer

PR for https://tyktech.atlassian.net/browse/TT-12775

This PR changes behavior to set `statedCL` to zero and continue processing the request, instead of returning an error with HTTP 411. 

The issue states the following:

> The bug aside, a proposed consideration for refinement of this feature; a potential memory optimisation point -
The current implementation reads the entire request and then checks if the size limit is exceeded.
Proposal: Read requests only up to the point of the set limit.

The implementation reads the request size from `http.Request.ContentLength`, it doesn't read the whole request body to count the bytes.

2024-12-02 09:26 UTC, buger commented
<p>I'm a bot and I 👍 this PR title. 🤖</p>

  <img src="https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif" width="400" />

2024-12-02 09:36 UTC, kofoworola approved these changes

2024-12-02 16:18 UTC, titpetric requested changes
As the bot says:

> The change from returning an error when 'Content-Length' header is missing to setting it to "0" might introduce unexpected behavior in downstream processing where actual content length is required.

As for the HTTP methods spec:

> HTTP request bodies are theoretically allowed for all methods except TRACE, however they are not commonly used except in PUT, POST and PATCH. Because of this, they may not be supported properly by some client frameworks, and you should not allow request bodies for GET, DELETE, TRACE, OPTIONS and HEAD methods.

I think the correct fix here is to ignore/skip content-length checks for the methods listed here. Content-length handling in respect to request size limit middleware if enabled, should *require content length* and respond with that 411 status code. Alternatively, wouldn't `r.Body` be nil?

2024-12-03 09:37 UTC, buraksezer commented
> As the bot says:
> 
> > The change from returning an error when 'Content-Length' header is missing to setting it to "0" might introduce unexpected behavior in downstream processing where actual content length is required.
> 
> As for the HTTP methods spec:
> 
> > HTTP request bodies are theoretically allowed for all methods except TRACE, however they are not commonly used except in PUT, POST and PATCH. Because of this, they may not be supported properly by some client frameworks, and you should not allow request bodies for GET, DELETE, TRACE, OPTIONS and HEAD methods.
> 
> I think the correct fix here is to ignore/skip content-length checks for the methods listed here. Content-length handling in respect to request size limit middleware if enabled, should _require content length_ and respond with that 411 status code. Alternatively, wouldn't `r.Body` be nil?

Request size limit middleware skips GET, DELETE, TRACE, OPTIONS and HEAD requests. I also bring back the original error message. `Content-Length` is required for POST, PUT and PATCH methods. If it doesn't exist, the middleware returns `Content length is required for this request` with HTTP 411 code. 

> Alternatively, wouldn't `r.Body` be nil?

I checked this, `r.Body` is always initialized.

2024-12-05 11:55 UTC, pvormste approved these changes

2024-12-06 08:19 UTC, buraksezer commented
Hey @titpetric, could you please review the changes again?

2024-12-09 09:18 UTC, titpetric commented on gateway/mw_request_size_limit_test.go
> +		// GET, DELETE, TRACE, OPTIONS and HEAD
Add a negative test case, POST, PATCH

2024-12-09 09:18 UTC, titpetric approved these changes

2024-12-09 09:18 UTC, merged

2024-12-10 07:59 UTC, buraksezer commented
/release to release-5.3

2024-12-10 10:06 UTC, buraksezer commented
/release to release-5.7